spring.application.name=td5-spring
spring.datasource.url=jdbc:postgresql://localhost:5432/mini_dish_db
spring.datasource.username=postgres
spring.datasource.password=aina
spring.datasource.driver-class-name=org.postgresql.Driver